# Generated by Django 4.2.11 on 2024-05-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_branch',
            new_name='Bank_branch',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_city',
            new_name='Bank_city',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_district',
            new_name='Bank_district',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_id',
            new_name='Bank_id',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_ifsc',
            new_name='Bank_ifsc',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_name',
            new_name='Bank_name',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='bank_state',
            new_name='Bank_state',
        ),
        migrations.AddField(
            model_name='bank_branches',
            name='Bank_address',
            field=models.CharField(default='Unknown Address', max_length=200),
        ),
    ]
