# Generated by Django 4.2.11 on 2024-05-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_bank_branch_bank_branches_bank_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_address',
            new_name='bank_address',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_branch',
            new_name='bank_branch',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_city',
            new_name='bank_city',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_district',
            new_name='bank_district',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_id',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_ifsc',
            new_name='bank_ifsc',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_name',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='bank_branches',
            old_name='Bank_state',
            new_name='bank_state',
        ),
    ]
