# Generated by Django 4.2.11 on 2024-05-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_bank_address_bank_branches_bank_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_branches',
            new_name='BankDetail',
        ),
    ]
